version: '3.6'
services:
  api:
    container_name: Api
    ports:
      - "8082:8080"
    image: 'node:alpine'
    working_dir: /home/node/app
    command:
      - /bin/sh
      - '-c'
      - './wait-for.sh mariadb:3306 -- npm i --save && npm run test_db'
      #- ' npm i --save && npm run test_db'
    volumes:
      - './api:/home/node/app'
    depends_on:
      - mariadb
    networks:
      - backend
  mariadb:
    image: mariadb:latest
    container_name: Database
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "db_tp2"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - backend
    expose:
      - '3306'
  react:
    container_name: App
    image: 'node:latest'
    working_dir: /home/node/app
    links:
      - mariadb
      - api
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm start'
      #- 'npm install && npm install -g serve && npm run build && serve -s build' # For prod testing
    ports:
      - '8081:3000'
    volumes:
      - './react-app:/home/node/app'
networks:
  backend:
    driver: bridge